version: 3
jobs:
  build:
    docker:
      - image: python:3.5
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: mydb
          MYSQL_USER: root
          MYSQL_PASSWORD: root
      - image: mysql:5.6
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 train.py
